# PCA via eigendecomposition
Using only numpy to do PCA so that I can convince my self I know what's going on

In [1]:
import numpy as np

In [85]:
X = np.array([[4,8,16,32],
              [2,4,8,16],
              [3,6,12,24]])

In [120]:
X = np.array([[4,8,16],
              [2,4,8]])

In [101]:
X = np.array([[4,8],
              [2,4],
              [1,2],
              [1.5,3]])

In [47]:
m = np.mean(X, axis=0)
m

array([ 3.,  6., 12., 24.])

In [48]:
sd = np.std(X, axis=0)
sd

array([0.81649658, 1.63299316, 3.26598632, 6.53197265])

In [49]:
X_std = (X - m)/sd
X_std

array([[ 1.22474487,  1.22474487,  1.22474487,  1.22474487],
       [-1.22474487, -1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [53]:
V = np.cov(X_std.T)
V

array([[1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5]])

In [86]:
values, vectors = np.linalg.eig(V)
print("Values")
print(values)
print("Vectors")
print(vectors)

Values
[8.8817842e-16 6.0000000e+00 0.0000000e+00 0.0000000e+00]
Vectors
[[-0.8660254   0.5         0.          0.        ]
 [ 0.28867513  0.5         0.81649658  0.        ]
 [ 0.28867513  0.5        -0.40824829 -0.70710678]
 [ 0.28867513  0.5        -0.40824829  0.70710678]]


In [87]:
scores = np.round(vectors.T.dot(X_std.T).T, 4)
print("Scores")
print(scores)

Scores
[[ 0.      2.4495  0.      0.    ]
 [-0.     -2.4495 -0.      0.    ]
 [ 0.      0.      0.      0.    ]]


Wrapping this up into a function:

In [102]:
def myPCA(X):
    m = np.mean(X, axis=0)
    sd = np.std(X, axis=0)
    X_std = (X - m)/sd
    V = np.cov(X_std.T)
    values = np.round(np.linalg.eig(V)[0], 4)
    loadings = np.round(np.linalg.eig(V)[1], 4)
    scores = np.round(loadings.T.dot(X_std.T).T, 3)
    print("Singular Values:")
    print(values)
    print("Loadings")
    print(loadings)
    print("Scores")
    print(scores)    
    return values, loadings, scores

In [121]:
myValues, myLoadings, myScores = myPCA(X)

Singular Values:
[-0.  6.  0.]
Loadings
[[-0.8165  0.5774  0.    ]
 [ 0.4082  0.5774 -0.7071]
 [ 0.4082  0.5774  0.7071]]
Scores
[[-0.     1.732  0.   ]
 [ 0.    -1.732  0.   ]]


In [138]:
sorted_values = myValues.argsort()[::-1]
sorted_values

array([1, 2, 0])

In [151]:
num_comp = 1
subset = sorted_values[:num_comp]
sub

array([1, 2])

In [152]:
myLoadings[:,subset]

array([[0.5774],
       [0.5774],
       [0.5774]])

In [153]:
X

array([[ 4,  8, 16],
       [ 2,  4,  8]])

### Checking results with sklearn PCA

In [88]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [104]:
scaler = StandardScaler()
X_std = scaler.fit_transform(X)
X_std

array([[ 1.6464639 ,  1.6464639 ],
       [-0.10976426, -0.10976426],
       [-0.98787834, -0.98787834],
       [-0.5488213 , -0.5488213 ]])

In [110]:
pca = PCA(2)

In [111]:
scores = pca.fit_transform(X_std)
scores

array([[ 2.32845158e+00,  7.80915792e-17],
       [-1.55230105e-01,  7.46239934e-18],
       [-1.39707095e+00,  1.35853139e-16],
       [-7.76150526e-01, -1.17533927e-17]])

In [112]:
pca.explained_variance_

array([2.00000000e+00, 6.18704995e-33])

In [113]:
pca.components_

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [114]:
pca.explained_variance_ratio_

array([1.00000000e+00, 3.09352497e-33])